# Generated by Django 5.2.4 on 2025-09-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
