# Generated by Django 5.2.4 on 2025-09-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_coursematerial_module_delete_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
