# Generated by Django 5.2.4 on 2025-09-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_coursematerial_module_delete_module'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_sessions', to='courses.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_sessions', to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attentive', models.BooleanField()),
                ('confidence', models.FloatField(default=0.0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_records', to='courses.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_records', to='users.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attention.attentionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
